// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsEt9CpNntc0aZ4CSAdu5jPrYNq45KGEg',
    appId: '1:335762528717:web:dfd6cd5bdf0cbddacf4c84',
    messagingSenderId: '335762528717',
    projectId: 'barangay-quest',
    authDomain: 'barangay-quest.firebaseapp.com',
    storageBucket: 'barangay-quest.firebasestorage.app',
    measurementId: 'G-TD1G8FQRKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS16R6N7zlLY4bhkijuxdR1d_Tg1OVX70',
    appId: '1:335762528717:android:7bd6e82a730ff3fdcf4c84',
    messagingSenderId: '335762528717',
    projectId: 'barangay-quest',
    storageBucket: 'barangay-quest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYsTSgY0pOiFmRIcuv4GUNnT84Uolgfs',
    appId: '1:335762528717:ios:f4d2991284f131b4cf4c84',
    messagingSenderId: '335762528717',
    projectId: 'barangay-quest',
    storageBucket: 'barangay-quest.firebasestorage.app',
    iosBundleId: 'com.example.barangayQuestFlutter',
  );
}
